server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/credx
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key=rzp_test_Shsg9HrYak9ENC
razorpay.secret=kO23CrrJnkkYxlZ62PlPQYr6